export const data = {
    'mass air flow sensor (maf) air flow rate': '0110',
    'throttle position': '0111',
    'commanded secondary air status': '0112',
    'oxygen sensors present (in 2 banks)': '0113',
    'oxygen sensor 1, a: voltage, b: short term fuel trim': '0114',
    'oxygen sensor 2, a: voltage, b: short term fuel trim': '0115',
    'oxygen sensor 3, a: voltage, b: short term fuel trim': '0116',
    'oxygen sensor 4, a: voltage, b: short term fuel trim': '0117',
    'oxygen sensor 5, a: voltage, b: short term fuel trim': '0118',
    'oxygen sensor 6, a: voltage, b: short term fuel trim': '0119',
    'pids supported [21 - 40]': '0120',
    'distance traveled with malfunction indicator lamp (mil) on': '0121',
    'fuel rail pressure (relative to manifold vacuum)': '0122',
    'fuel rail pressure (diesel, or gasoline direct inject)': '0123',
    'oxygen sensor 1, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0124',
    'oxygen sensor 2, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0125',
    'oxygen sensor 3, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0126',
    'oxygen sensor 4, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0127',
    'oxygen sensor 5, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0128',
    'oxygen sensor 6, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '0129',
    'warm-ups since codes cleared': '0130',
    'distance traveled since codes cleared': '0131',
    'evap. system vapor pressure': '0132',
    'absolute barometric pressure': '0133',
    'oxygen sensor 1, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0134',
    'oxygen sensor 2, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0135',
    'oxygen sensor 3, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0136',
    'oxygen sensor 4, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0137',
    'oxygen sensor 5, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0138',
    'oxygen sensor 6, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '0139',
    'pids supported [41 - 60]': '0140',
    'monitor status this drive cycle': '0141',
    'control module voltage': '0142',
    'absolute load value': '0143',
    'fuel-air commanded equivalence ratio': '0144',
    'relative throttle position': '0145',
    'ambient air temperature': '0146',
    'absolute throttle position b': '0147',
    'absolute throttle position c': '0148',
    'accelerator pedal position d': '0149',
    'maximum value for air flow rate from mass air flow sensor': '0150',
    'fuel type': '0151',
    'ethanol fuel %': '0152',
    'absolute evap. system vapor pressure': '0153',
    'evap. system vapor pressure': '0154',
    'short term secondary oxygen sensor trim bank 1 and bank 3': '0155',
    'long term secondary oxygen sensor trim bank 1 and bank 3': '0156',
    'short term secondary oxygen sensor trim bank 2 and bank 4': '0157',
    'long term secondary oxygen sensor trim bank 2 and bank 4': '0158',
    'fuel rail pressure (absolute)': '0159',
    'pids supported [61 - 80]': '0160',
    'driver\'s demand engine - percent torque': '0161',
    'actual engine - percent torque': '0162',
    'engine reference torque': '0163',
    'engine percent torque data': '0164',
    'auxiliary input / output supported': '0165',
    'mass air flow sensor': '0166',
    'engine coolant temperature': '0167',
    'intake air temperature sensor': '0168',
    'actual egr, commanded egr, and egr error': '0169',
    'boost pressure control': '0170',
    'variable geometry turbo (vgt) control': '0171',
    'wastegate control': '0172',
    'exhaust pressure': '0173',
    'turbocharger rpm': '0174',
    'turbocharger temperature': '0175',
    'turbocharger temperature': '0176',
    'charge air cooler temperature (cact)': '0177',
    'exhaust gas temperature (egt) bank 1': '0178',
    'exhaust gas temperature (egt) bank 2': '0179',
    'pids supported [81 - a0]': '0180',
    'engine run time for auxiliary emissions control device(aecd)': '0181',
    'engine run time for auxiliary emissions control device(aecd)': '0182',
    'nox sensor': '0183',
    'manifold surface temperature': '0184',
    'nox reagent system': '0185',
    'particulate matter (pm) sensor': '0186',
    'intake manifold absolute pressure': '0187',
    'scr induce system': '0188',
    'run time for aecd #11-#15': '0189',
    'wwh-obd vehicle obd system information': '0190',
    'wwh-obd vehicle obd system information': '0191',
    'fuel system control': '0192',
    'wwh-obd vehicle obd counters support': '0193',
    'nox warning and inducement system': '0194',
    'exhaust gas temperature sensor': '0198',
    'exhaust gas temperature sensor': '0199',
    'pids supported [01 - 20]': '0100',
    'monitor status since dtcs cleared. (includes malfunction indicator lamp (mil), status and number of dtcs, components tests, dtc readiness checks)': '0101',
    'freeze dtc': '0102',
    'fuel system status': '0103',
    'calculated engine load': '0104',
    'engine coolant temperature': '0105',
    'short term fuel trim—bank 1': '0106',
    'long term fuel trim—bank 1': '0107',
    'short term fuel trim—bank 2': '0108',
    'long term fuel trim—bank 2': '0109',
    'fuel pressure (gauge pressure)': '010A',
    'intake manifold absolute pressure': '010B',
    'engine speed': '010C',
    'vehicle speed': '010D',
    'timing advance': '010E',
    'intake air temperature': '010F',
    'oxygen sensor 7, a: voltage, b: short term fuel trim': '011A',
    'oxygen sensor 8, a: voltage, b: short term fuel trim': '011B',
    'obd standards this vehicle conforms to': '011C',
    'oxygen sensors present (in 4 banks)': '011D',
    'auxiliary input status': '011E',
    'run time since engine start': '011F',
    'oxygen sensor 7, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '012A',
    'oxygen sensor 8, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio': '012B',
    'commanded egr': '012C',
    'egr error': '012D',
    'commanded evaporative purge': '012E',
    'fuel tank level input': '012F',
    'oxygen sensor 7, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '013A',
    'oxygen sensor 8, a: voltage, b: fuel-air commanded equivalence ratio, c: fuel-air actual equivalence ratio, d: short term fuel trim': '013B',
    'catalyst temperature bank 1, sensor 1': '013C',
    'catalyst temperature bank 2, sensor 1': '013D',
    'catalyst temperature bank 1, sensor 2': '013E',
    'catalyst temperature bank 2, sensor 2': '013F',
    'accelerator pedal position e': '014A',
    'accelerator pedal position f': '014B',
    'commanded throttle actuator': '014C',
    'time run with mil on': '014D',
    'time since trouble codes cleared': '014E',
    'maximum value for equivalence ratio, oxygen sensor voltage, oxygen sensor current, and intake manifold absolute pressure': '014F',
    'relative accelerator pedal position': '015A',
    'hybrid battery pack remaining life': '015B',
    'engine oil temperature': '015C',
    'fuel injection timing': '015D',
    'engine fuel rate': '015E',
    'emission requirements to which vehicle is designed': '015F',
    'commanded diesel intake air flow control and relative intake air flow position': '016A',
    'exhaust gas recirculation temperature': '016B',
    'commanded throttle actuator control and relative throttle position': '016C',
    'fuel pressure control system': '016D',
    'injection pressure control system': '016E',
    'turbocharger compressor inlet pressure': '016F',
    'diesel particulate filter (dpf) / differential pressure': '017A',
    'diesel particulate filter (dpf)': '017B',
    'diesel particulate filter (dpf) temperature': '017C',
    'nox nte control area status': '017D',
    'pm nte control area status': '017E',
    'engine run time': '017F',
    'run time for aecd #16-#20': '018A',
    'diesel aftertreatment': '018B',
    'o2 sensor (wide range)': '018C',
    'throttle position g': '018D',
    'engine friction - percent torque': '018E',
    'pm sensor bank 1 & 2': '018F',
    'hybrid/ev vehicle system data, battery, voltage': '019A',
    'diesel exhaust fluid sensor data': '019B',
    'o2 sensor data': '019C',
    'engine fuel rate': '019D',
    'engine exhaust flow rate': '019E',
    'fuel system percentage use': '019F',
    'pids supported [a1 - c0]': '01A0',
    'nox sensor corrected data': '01A1',
    'cylinder fuel rate': '01A2',
    'evap system vapor pressure': '01A3',
    'transmission actual gear': '01A4',
    'commanded diesel exhaust fluid dosing': '01A5',
    'odometer': '01A6',
    'nox sensor concentration sensors 3 and 4': '01A7',
    'nox sensor corrected concentration sensors 3 and 4': '01A8',
    'abs disable switch state': '01A9',
    'pids supported [c1 - e0]': '01AA',
    'dtc that caused freeze frame to be stored': '0202',
    'request trouble codes': '0300',
    'clear trouble codes / malfunction indicator lamp (mil) / check engine light': '0400',
    'obd monitor ids supported (#01 - #20)': '050100',
    'o2 sensor monitor bank 1 sensor 1': '050101',
    'o2 sensor monitor bank 1 sensor 2': '050102',
    'o2 sensor monitor bank 1 sensor 3': '050103',
    'o2 sensor monitor bank 1 sensor 4': '050104',
    'o2 sensor monitor bank 2 sensor 1': '050105',
    'o2 sensor monitor bank 2 sensor 2': '050106',
    'o2 sensor monitor bank 2 sensor 3': '050107',
    'o2 sensor monitor bank 2 sensor 4': '050108',
    'o2 sensor monitor bank 3 sensor 1': '050109',
    'o2 sensor monitor bank 3 sensor 2': '05010A',
    'o2 sensor monitor bank 3 sensor 3': '05010B',
    'o2 sensor monitor bank 3 sensor 4': '05010C',
    'o2 sensor monitor bank 4 sensor 1': '05010D',
    'o2 sensor monitor bank 4 sensor 2': '05010E',
    'o2 sensor monitor bank 4 sensor 3': '05010F',
    'o2 sensor monitor bank 4 sensor 4': '050110',
    'o2 sensor monitor bank 1 sensor 1': '050201',
    'o2 sensor monitor bank 1 sensor 2': '050202',
    'o2 sensor monitor bank 1 sensor 3': '050203',
    'o2 sensor monitor bank 1 sensor 4': '050204',
    'o2 sensor monitor bank 2 sensor 1': '050205',
    'o2 sensor monitor bank 2 sensor 2': '050206',
    'o2 sensor monitor bank 2 sensor 3': '050207',
    'o2 sensor monitor bank 2 sensor 4': '050208',
    'o2 sensor monitor bank 3 sensor 1': '050209',
    'o2 sensor monitor bank 3 sensor 2': '05020A',
    'o2 sensor monitor bank 3 sensor 3': '05020B',
    'o2 sensor monitor bank 3 sensor 4': '05020C',
    'o2 sensor monitor bank 4 sensor 1': '05020D',
    'o2 sensor monitor bank 4 sensor 2': '05020E',
    'o2 sensor monitor bank 4 sensor 3': '05020F',
    'o2 sensor monitor bank 4 sensor 4': '050210',
    'service 9 supported pids (01 to 20)': '0900',
    'vin message count in pid 02. only for iso 9141-2, iso 14230-4 and sae j1850': '0901',
    'vehicle identification number (vin)': '0902',
    'calibration id message count for pid 04. only for iso 9141-2, iso 14230-4 and sae j1850': '0903',
    'calibration id': '0904',
    'calibration verification numbers (cvn) message count for pid 06. only for iso 9141-2, iso 14230-4 and sae j1850': '0905',
    'calibration verification numbers (cvn) several cvn can be output (4 bytes each) the number of cvn and calid must match': '0906',
    'in-use performance tracking message count for pid 08. only for iso 9141-2, iso 14230-4 and sae j1850': '0907',
    'in-use performance tracking for spark ignition vehicles': '0908',
    'ecu name message count for pid 0a': '0909',
    'ecu name': '090A',
    'in-use performance tracking for compression ignition vehicles': '090B',
};
